# Generated by Django 5.1.5 on 2025-03-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
