# Generated by Django 5.1.5 on 2025-03-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_employee_table_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_table',
            name='joining_date',
        ),
    ]
