# Generated by Django 5.1.5 on 2025-03-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_adassignment_adcampaign_campaignapproval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignapproval',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignapproval',
            name='client',
        ),
        migrations.DeleteModel(
            name='AdCampaign',
        ),
        migrations.DeleteModel(
            name='CampaignApproval',
        ),
    ]
