# Generated by Django 5.1.5 on 2025-03-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adassignment',
            name='ad_creative',
        ),
        migrations.RemoveField(
            model_name='adassignment',
            name='ad_space',
        ),
        migrations.RemoveField(
            model_name='adassignment',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='adcreative',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='finaladsubmission',
            name='ad_creative',
        ),
        migrations.RemoveField(
            model_name='adproject',
            name='CLIENT',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_request',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='client',
        ),
        migrations.RemoveField(
            model_name='finaladcreative',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='finaladsubmission',
            name='client',
        ),
        migrations.RemoveField(
            model_name='finaladsubmission',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='AdSpace',
        ),
        migrations.DeleteModel(
            name='AdAssignment',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.DeleteModel(
            name='AdCreative',
        ),
        migrations.DeleteModel(
            name='AdProject',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='FinalAdCreative',
        ),
        migrations.DeleteModel(
            name='FinalAdSubmission',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
