# Generated by Django 5.1.5 on 2025-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_campaign_request_status_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign_request',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
