# Generated by Django 5.1.5 on 2025-03-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_campaign_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='workload',
            field=models.IntegerField(default=0),
        ),
    ]
