# Generated by Django 5.1.5 on 2025-03-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_table',
            name='workload',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
    ]
