# Generated by Django 5.1.5 on 2025-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_remove_task_completed_remove_task_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creative_file',
            field=models.FileField(blank=True, null=True, upload_to='creatives/'),
        ),
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by_cd',
            field=models.BooleanField(default=False),
        ),
    ]
