# Generated by Django 5.1.5 on 2025-03-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_remove_creativeupload_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.employee_table'),
        ),
    ]
