# Generated by Django 5.1.5 on 2025-03-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_finalcreative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcreative',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.employee_table'),
        ),
    ]
