# Generated by Django 5.1.5 on 2025-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_alter_finalcreative_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcreative',
            name='approved_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
