# Generated by Django 5.1.5 on 2025-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_finalcreative_approved_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcreative',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
