# Generated by Django 5.1.5 on 2025-03-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_finalcreative_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_table',
            name='status',
            field=models.CharField(blank=True, default='unread', max_length=20, null=True),
        ),
    ]
